game:
  title: Planet Explorer
  welcome: Welcome to

logging:
  colored: true
  level: debug
  report_caller: true

gui:
  fullscreen: false
  fg_color: [255,255,255]
  bg_color: [0,0,0]
  cursor_color: [0,102,0]
  map_area:
    width: 200
    height: 90
  text_area:
    height: 6

npcs:
  count: 8
  chr: â˜º
  fg_color: [0,255,0]
  bg_color: [0,0,0]
  init_x: 7
  init_y: 20

player:
  name: "Player"
  chr: "@"
  stats:
    max_hp: 80
    starting_hp: 80
    defense: 2
    power: 8
  fg_color: [255,255,0]
  bg_color: [0,0,0]
  view_range:
    tile_count: 8

monsters:
  fg_color: [255,0,0]
  bg_color: [0,0,0]
  view_range:
    tile_count: 3
  goblin:
    name: "Goblin"
    chr: "g"
    stats:
      max_hp: 10
      starting_hp: 10
      defense: 1
      power: 2
  orc:
    name: "Orc"
    chr: "o"
    stats:
      max_hp: 20
      starting_hp: 20
      defense: 2
      power: 3

rooms:
  max_count: 30
  min_size: 6
  max_size: 10
  max_monsters: 4
  max_items: 2

items:
  health_potion:
    name: "Health Potion"
    chr: "i"
    fg_color: [255,0,255]
    bg_color: [0,0,0]
    power: 8
  magic_missile_scroll:
    name: "Magic Missile Scroll"
    chr: ")"
    fg_color: [0,255,255]
    bg_color: [0,0,0]
    range: 6
    power: 8
  fireball_scroll:
    name: "Fireball Scroll"
    chr: ")"
    fg_color: [255,153,0]
    bg_color: [0,0,0]
    radius: 3
    range: 6
    power: 20
  confusion_scroll:
    name: "Confusion Scroll"
    chr: ")"
    fg_color: [255,153,204]
    bg_color: [0,0,0]
    range: 6
    power: 4 # this is number of turns
